apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: skupperfrontend
  description: A cool quarkus app
  annotations:
    backstage.io/source-location: url:
    backstage.io/techdocs-ref: dir:.
    #argocd/app-name: skupperfrontend
  tags:
    - java
    - quarkus
  links:
    - url: https://github.com/pittar-rhdh/
      title: Open in Dev Spaces
      icon: web
    - url: https://www.redhat.com/en/blog/channel/hybrid-cloud-infrastructure
      title: Red Hat Blog
      icon: web
spec:
  type: service
  lifecycle: production
  owner: group:default/teamlead
